'use client'

import { FormEvent, useState } from 'react'
import { createClient } from '@/lib/supabase/client'
import { useRouter } from 'next/navigation'
import SiteSettingsForm from './site-settings-form'

type Property = { id: string; title: string; location: string; price: string | number; area: string | number; description: string | null; status: string | null; cover_image: string | null }
type FormState = Omit<Property, 'id'>
type SiteSettings = { brandName: string; logoUrl: string; heroImageUrl: string; heroTitle: string; heroDescription: string; primaryColor: string; accentColor: string }
const empty: FormState = { title: '', location: '', price: '', area: '', description: '', status: 'Casa · Venta', cover_image: '' }

export default function AdminDashboard({ email, initialProperties, initialSettings }: { email: string; initialProperties: Property[]; initialSettings: Partial<SiteSettings> }) {
  const router = useRouter(); const [properties, setProperties] = useState(initialProperties); const [form, setForm] = useState<FormState>(empty); const [editing, setEditing] = useState<string | null>(null); const [message, setMessage] = useState('')
  const setField = (field: keyof FormState, value: string) => setForm((current) => ({ ...current, [field]: value }))
  function edit(property: Property) { setEditing(property.id); setForm({ title: String(property.title ?? ''), location: String(property.location ?? ''), price: property.price, area: property.area, description: property.description ?? '', status: property.status ?? '', cover_image: property.cover_image ?? '' }); window.scrollTo({ top: 0, behavior: 'smooth' }) }
  function reset() { setEditing(null); setForm(empty); setMessage('') }
  async function save(event: FormEvent) { event.preventDefault(); setMessage(''); const payload = { ...form, price: form.price === '' ? null : Number(form.price), area: form.area === '' ? null : Number(form.area) }; const supabase = createClient(); const result = editing ? await supabase.from('properties').update(payload).eq('id', editing).select().single() : await supabase.from('properties').insert(payload).select().single(); if (result.error) { setMessage('No se pudo guardar. Revisá los campos e intentá nuevamente.'); return } if (editing) setProperties((items) => items.map((item) => item.id === editing ? result.data : item)); else setProperties((items) => [result.data, ...items]); reset(); setMessage('Cambios guardados correctamente.') }
  async function remove(id: string) { if (!window.confirm('¿Eliminar esta propiedad?')) return; const { error } = await createClient().from('properties').delete().eq('id', id); if (!error) setProperties((items) => items.filter((item) => item.id !== id)) }
  async function signOut() { await createClient().auth.signOut(); router.replace('/'); router.refresh() }
  return <main className="admin-shell"><header className="admin-header"><a className="admin-brand" href="/">CAROLINA<br />DE ORTA</a><div><p className="admin-eyebrow">PANEL PRIVADO</p><span className="admin-muted">{email}</span></div><button className="admin-link-button" onClick={signOut}>Cerrar sesión</button></header><div className="admin-content"><SiteSettingsForm initialValues={initialSettings} /><div className="admin-title-row"><div><p className="admin-eyebrow">CONTENIDO</p><h1>Propiedades</h1><p className="admin-muted">Administrá los espacios que aparecen en tu sitio público.</p></div><a className="admin-outline" href="/">Ver sitio</a></div><section className="admin-panel"><h2>{editing ? 'Editar propiedad' : 'Nueva propiedad'}</h2><form className="property-form" onSubmit={save}><label>Título<input value={form.title} onChange={(event) => setField('title', event.target.value)} required /></label><label>Ubicación<input value={form.location} onChange={(event) => setField('location', event.target.value)} required /></label><label>Precio<input type="number" value={form.price} onChange={(event) => setField('price', event.target.value)} required /></label><label>Superficie<input type="number" value={form.area} onChange={(event) => setField('area', event.target.value)} required /></label><label>Estado<input value={form.status ?? ''} onChange={(event) => setField('status', event.target.value)} /></label><label>Imagen de portada (URL)<input type="url" value={form.cover_image ?? ''} onChange={(event) => setField('cover_image', event.target.value)} /></label><label className="full-field">Descripción<textarea rows={4} value={form.description ?? ''} onChange={(event) => setField('description', event.target.value)} /></label><div className="form-actions"><button className="admin-button" type="submit">{editing ? 'Guardar cambios' : 'Crear propiedad'}</button>{editing && <button className="admin-cancel" type="button" onClick={reset}>Cancelar</button>}{message && <span className="admin-success">{message}</span>}</div></form></section><section className="admin-panel"><h2>Propiedades existentes <span>({properties.length})</span></h2><div className="admin-table">{properties.length === 0 ? <p className="admin-muted">Todavía no hay propiedades cargadas.</p> : properties.map((property) => <div className="admin-row" key={property.id}><div><strong>{property.title}</strong><span>{property.location} · {property.status}</span></div><div className="admin-row-actions"><button onClick={() => edit(property)}>Editar</button><button onClick={() => remove(property.id)}>Eliminar</button></div></div>)}</div></section><section className="admin-panel admin-coming"><h2>Otros contenidos</h2><p className="admin-muted">La estructura para editar textos, proyectos, actualidad e imágenes queda preparada para la próxima etapa. La web pública mantiene sus valores actuales.</p></section></div></main>
}
